services:
  - type: web
    name: visual-monitor-web
    env: docker
    dockerfilePath: app/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "set-in-dashboard"
      - key: REDIS_URL
        value: "set-in-dashboard"
      - key: S3_ENDPOINT
        value: "https://s3.eu-central-003.backblazeb2.com"
      - key: S3_REGION
        value: "eu-central-003"
      - key: S3_BUCKET
        value: "visual-monitor-bucket"
      - key: AWS_ACCESS_KEY_ID
        value: "set-in-dashboard"
      - key: AWS_SECRET_ACCESS_KEY
        value: "set-in-dashboard"
      - key: SENDGRID_API_KEY
        value: "set-in-dashboard"
      - key: EMAIL_FROM
        value: "notifications@example.com"
      - key: JWT_SECRET
        value: "change-me-to-a-long-random-string"
      - key: NEXT_PUBLIC_BASE_URL
        value: "https://your-render-web-url.onrender.com"

  - type: worker
    name: visual-monitor-worker
    env: docker
    dockerfilePath: worker/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "set-in-dashboard"
      - key: REDIS_URL
        value: "set-in-dashboard"
      - key: S3_ENDPOINT
        value: "https://s3.eu-central-003.backblazeb2.com"
      - key: S3_REGION
        value: "eu-central-003"
      - key: S3_BUCKET
        value: "visual-monitor-bucket"
      - key: AWS_ACCESS_KEY_ID
        value: "set-in-dashboard"
      - key: AWS_SECRET_ACCESS_KEY
        value: "set-in-dashboard"
      - key: SENDGRID_API_KEY
        value: "set-in-dashboard"
      - key: EMAIL_FROM
        value: "notifications@example.com"
      - key: JWT_SECRET
        value: "change-me-to-a-long-random-string"
      - key: TEST_URL
        value: "https://example.com"
